### ISSUE TITLE
I can not distinguish the windows if both windows of an app and Hyper have the same background colour

### ISSUE THREAD

**Issue by gusbemacbe** [arcticicestudio/nord-hyper#31]
## Issue Type

Improvement

## Description

One windows of any app which has Nord theme and another window of Hyper have the same background colour and i can not distinguish the windows. For example, see the screenshot:

![image](https://user-images.githubusercontent.com/2257024/40590597-ae0ef3fe-61d7-11e8-9aa9-b8b3881d0bd2.png)

### Steps to Reproduce

1. Open any app with Nord theme and Hyper
2. Notice and compare the windows and the background colour

### Expected Behaviour

You can not distinguish because they have the same background colour and Hyper does not have drop shadow or border. 

Yes, I was aware that there is a border, but border is too thin, then I can not see the bord or the shadow.

### Actual Behaviour

Same windows background colours. There is no border or drop shadow in Hyper.

### Environment and Versions

* What is the version of Nord Hyper you are running? The latest 
* What is the name and the version of your OS? Ubuntu 18.04 GNOME 3, KDE Plasma and XFCE
* Have you tried to reproduce it on different OS environments and if yes is the behaviour the same for all? Yes
* Which Node.js and Hyper version are you running? Hyper 2.1.0 (Canary) and Node 9.11.1
* Are you using any additional CLI arguments for Node.js? No

## Stack Trace and Error Messages

No warning and error messages

## References

Border and drop shadow

## Potential solution

Add a border colour, border-radius and width or drop shadow enabling. 

## Additional information

I made a pull request unrelated to Hyper Nord and called you to review. I refer to the https://github.com/arcticicestudio/nord/pull/103

**Comment by arcticicestudio** [comment]
This depends on the [window manager][wm] your're using. It is responsible to handle such window effects, not the application itself. I'm using Arch Linux with GNOME 3.28+ which uses the [Mutter][mutt] WM. There are also standalone window manager (I'm using it for my i3/Sway sessions) like e.g. [compiz][comp] that is a [Compositing window manager][cwm].

If you're using Ubuntu it should work out-of-the-box since it uses GNOME (Mutter) or older versions that use the deprecated _Unity_ engine. XFCE for example uses the [Xfwm][] WM.

You should check your WM settings if window drop-shadows are disabled or if you've installed any GNOME Shell extensions that overrides or conflicts with drop-shadows.

> Negative reproduction screenshot on Arch Linux with GNOME 3.28

![gh-31-reproduction-negative](https://user-images.githubusercontent.com/7836623/40604254-cc26662e-625e-11e8-92d8-63d6d1943bf6.png) 

[wm]: https://wiki.archlinux.org/index.php/Window_manager
[mutt]: https://en.wikipedia.org/wiki/Mutter_(software)
[cwm]: https://en.wikipedia.org/wiki/Compositing_window_manager
[comp]: https://wiki.archlinux.org/index.php/Compiz
[xfwm]: https://wiki.archlinux.org/index.php/Xfwm

**Comment by gusbemacbe** [comment]
In the screenshot I showed you, it is KDE. Now I am at GNOME and it appeared normally with drop shadow. But I would like to stick with KDE. At KDE, it appears with no drop shadow.

**Comment by arcticicestudio** [comment]
Also thanks for your PR in the main repository, I'm aware of it, but my free time to work on my and other projects is currently limited due to my job and study. There are currently over 500 PR and issue notifications on my TODO list so I'll review the PR as soon as I've got more time again. Thanks for your understanding.

> But I would like to stick with KDE. At KDE, it appears with no drop shadow.

I've never used KDE, but I'm sure that the used WM is able to accomplish this (I know they got more complicated animations working like e.g. transparency/vibrancy for content behind windows). Please check out their documentation or any support and community chats like Slack to enable drop-shadows. Like already mentioned drop-shadows are never managed by the application itself but the running window manager (regardless of the OS, e.g. macOS and Windows also using their own non-open-source implementations).
