### ISSUE TITLE
Release version 0.1.1 on NPM

### ISSUE THREAD

**Issue by zovt** [arcticicestudio/nord-hyper#5]
The latest currently available is 0.1.0

**Comment by arcticicestudio** [comment]
Well, this is strange :open_mouth:
I've released version 0.1.1 after I've pushed the tag to the repository and everything worked fine, but for whatever reason the latest version on the NPM site is still `0.1.0` 😒 

I've tried to publish it again, but getting this error:
>  "You cannot publish over the previously published version 0.1.1." : nord-hyper

Also, note the sentence on the right side on the NPM package website which says
> **0.1.0** is the latest of **2** releases

where the second version can only be the `v0.1.1` tag.

**Comment by zovt** [comment]
No problem :) good luck, NPM can be a pain

**Comment by arcticicestudio** [comment]
Alright, seems like it is no recommended to `npm publish` with the `--tag` flag. NPM uses so called *dist-tags* which always refers to `latest` like *Docker*. I've been using the `--tag` flag because thats the way I publish Atom package updates via `apm`.
Unfortunately there is absolute no more way to `unpublish` and republish the same tagged version **ever** again because [`npm publish -f` has been removed](http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f).
That said I'll have to publish a new "empty" version which only fulfills the purpose to bump the NPM version to `latest`.

**Comment by arcticicestudio** [comment]
🚢 Shipped NPM package release version [0.2.0](https://github.com/arcticicestudio/nord-hyper/releases/tag/v0.2.0) with a new feature and now published via `npm publish` (without the `--tag` option) which fixed the problem 😄

**Comment by zovt** [comment]
nice! 😄
